### ISSUE TITLE
fetch up to date emoji list from internet

### ISSUE THREAD

**Issue by GROOOOAAAARK** [GROOOOAAAARK/zig-commit-emojis#6]
## Problem

Static data (emojis and their description) in the CLI may not be up to date, and if not, we can't really know when and what is missing.

## Expected Behavior

Fetch the published [official repo json file](https://github.com/carloscuesta/gitmoji/blob/master/packages/gitmojis/src/gitmojis.json) containing gitmojis and descriptions, load as gitmojiconfig array and work on this instead of the static one.
If offline or error while transforming or fetching data, print simple message for user

## TODO

- [ ] fetch up to date git emoji json from the gitmoji repo
- [ ] transform the json in an array of gitmojiconfig to use in the search and list methods
  - [ ] happyflow
  - [ ] fetch error (offline, etc) => use local version (print message "offline use")
  - [ ] transform errors => use local version (print message "error format")
